import { GenerateUsernameFn } from "@floatingfile/types";

const animals = [
  "Alligator",
  "Alpaca",
  "Donkey",
  "Bear",
  "Beaver",
  "Bison",
  "Boar",
  "Buffalo",
  "Butterfly",
  "Camel",
  "Caribou",
  "Cat",
  "Cattle",
  "Cheetah",
  "Chicken",
  "Cod",
  "Coyote",
  "Crab",
  "Crane",
  "Crow",
  "Deer",
  "Dog",
  "Dolphin",
  "Dove",
  "Duck",
  "Eagle",
  "Eland",
  "Elephant",
  "Elk",
  "Emu",
  "Falcon",
  "Ferret",
  "Finch",
  "Fish",
  "Flamingo",
  "Fox",
  "Gazelle",
  "Gerbil",
  "Giraffe",
  "Goat",
  "Goldfish",
  "Goose",
  "Hamster",
  "Horse",
  "Koala",
  "Leopard",
  "Lion",
  "Llama",
  "Lobster",

  "Manatee",
  "Monkey",
  "Moose",
  "Octopus",
  "Ostrich",
  "Otter",
  "Owl",
  "Panther",
  "Parrot",
  "Peafowl",
  "Pelican",
  "Penguin",
  "Pig",
  "Pigeon",
  "Pony",
  "Rabbit",
  "Reindeer",
  "Seal",
  "Shark",
  "Sheep",
  "Snail",
  "Sparrow",
  "Squid",
  "Squirrel",
  "Stork",
  "Swallow",
  "Swan",
  "Tiger",
  "Turkey",
  "Turtle",
  "Wallaby",
  "Walrus",
  "Whale",
  "Wolf",
  "Zebra",
];

const colors = {
  aqua: "#00ffff",
  black: "#000000",
  blue: "#0000ff",
  brown: "#a52a2a",
  coral: "#ff7f50",
  crimson: "#dc143c",
  cyan: "#00ffff",
  fuchsia: "#ff00ff",
  gold: "#ffd700",
  gray: "#808080",
  green: "#008000",
  grey: "#808080",
  hotpink: "#ff69b4",
  indigo: "#4b0082",
  lime: "#00ff00",
  magenta: "#ff00ff",
  maroon: "#800000",
  navy: "#000080",
  olive: "#808000",
  olivedrab: "#6b8e23",
  orange: "#ffa500",
  orchid: "#da70d6",
  peru: "#cd853f",
  pink: "#ffc0cb",
  plum: "#dda0dd",
  purple: "#800080",
  red: "#ff0000",
  salmon: "#fa8072",
  sienna: "#a0522d",
  silver: "#c0c0c0",
  tan: "#d2b48c",
  teal: "#008080",
  thistle: "#d8bfd8",
  tomato: "#ff6347",
  violet: "#ee82ee",
};

export const generateUsername: GenerateUsernameFn = () => {
  const animal: string =
    animals[(animals.length * Math.random()) << 0].toLowerCase();
  const colorNames: string[] = Object.keys(colors);
  const color: string = colorNames[(colorNames.length * Math.random()) << 0];
  const username = `${color}-${animal}`;
  return { username };
};
