enum SpaceEvents {
  CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED",
  FILES_UPDATED = "FILES_UPDATED",
  HISTORY_UPDATED = "HISTORY_UPDATED",
  USERS_UPDATED = "USERS_UPDATED",
  SPACE_DELETED = "SPACE_DELETED",
}

export { SpaceEvents };
