module.exports = {
	BASE_API_URL: process.env.REACT_APP_BASE_API_URL,
	ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT,
	SOCKET_URL: process.env.REACT_APP_SOCKET_URL,
	USERNAME_STORAGE_KEY: process.env.REACT_APP_USERNAME_STORAGE_KEY,
	ORIGIN: process.env.REACT_APP_ORIGIN,
	LAST_VISIT_STORAGE_KEY: process.env.REACT_APP_LAST_VISIT_STORAGE_KEY,
};
